# Reproducible Research: Peer Assessment 2
# Title

synopis synopsis
synopsis synopsis

## Data Processing
We first change the working directory to the repository location and load our datafile.

```{r echo=TRUE}
library(plyr)
library(ggplot2)

setwd("~/GitHub/RepData_PeerAssessment2")
#data<-read.csv(bzfile("data/repdata-data-StormData.csv.bz2"),header=TRUE, nrows=200000)
data<-read.csv(bzfile("data/repdata-data-StormData.csv.bz2"),header=TRUE, nrows=300000)
stormData<-data[,c("EVTYPE","FATALITIES","INJURIES","PROPDMG","PROPDMGEXP","CROPDMG","CROPDMGEXP")]
data<-NULL

stormData$PROPDMG <- ifelse(stormData$PROPDMGEXP %in% c("k","K"),stormData$PROPDMG * 1000,    
     ifelse(stormData$PROPDMGEXP %in% c("m","M"),stormData$PROPDMG * 1000000,
          ifelse(stormData$PROPDMGEXP %in% c("b","M"),stormData$PROPDMG * 1000000000,  
            stormData$PROPDMG))) 

stormData$CROPDMG <- ifelse(stormData$CROPDMGEXP %in% c("k","K"),stormData$CROPDMG * 1000,
       ifelse(stormData$CROPDMGEXP %in% c("m","M"),stormData$CROPDMG * 1000000,
               ifelse(stormData$CROPDMGEXP %in% c("b","B"),stormData$CROPDMG * 1000000000,
                      stormData$CROPDMG)))


#Remove all unused variables
stormData$PROPDMGEXP<-NULL
stormData$CROPDMGEXP<-NULL

summedStormData<-ddply(stormData,~EVTYPE,summarise,FATALITIES=sum(FATALITIES),INJURIES=sum(INJURIES), PROPDMG=sum(PROPDMG),CROPDMG=sum(CROPDMG))
stormData<-NULL

```

## Results
```{r echo=TRUE}
library(ggplot2)

summedStormData<-arrange(summedStormData,desc(summedStormData$FATALITIES))
fatalitiesData<-summedStormData[1:10,]
fatalitiesData
g<-ggplot(fatalitiesData, aes(x=reorder(EVTYPE, -FATALITIES), y=FATALITIES)) 
g + geom_bar(stat="identity",width=.5)
g + labs(x="Event", y="Fatalities", title="Top 10 Causes of Storm-Related Fatalities") 
g + theme(axis.text.x  = element_text(angle=45, vjust=0.5))

summedStormData<-arrange(summedStormData,desc(summedStormData$INJURIES))
injuriesData<-summedStormData[1:10,]
injuriesData

summedStormData<-arrange(summedStormData,desc(summedStormData$PROPDMG))
propDamageData<-summedStormData[1:10,]
propDamageData$PROPDMG <- propDamageData$PROPDMG/1000000
propDamageData
g <- ggplot(propDamageData, aes(x=reorder(EVTYPE, -PROPDMG), y=PROPDMG))
g + geom_bar(stat="identity",width=.5) 
g + labs(x="Event", y="Property Damage", title="Top 10 Causes of Storm-Related Property Damage")
g + theme(axis.text.x  = element_text(angle=45, vjust=0.5))

summedStormData<-arrange(summedStormData,desc(summedStormData$CROPDMG))
cropDamageData<-summedStormData[1:10,]
cropDamageData$CROPDMG <- cropDamageData$CROPDMG/1000000
cropDamageData
g<-ggplot(cropDamageData, aes(x=reorder(EVTYPE, -CROPDMG), y=CROPDMG))
g + geom_bar(stat="identity",width=.5)
g + labs(x="Event", y="Crop Damage", title="Top 10 Causes of Storm-Related Crop Damage")
g + theme(axis.text.x  = element_text(angle=45, vjust=0.5))

```

